[package]
edition = "2021"
name = "data_doc"
version = "0.1.0"
description = "Getting doc string at runtime"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.1"
