[package]
description = "CosmWasm swiss-army knife configured for Osmosis by default, but trivial to make it work for other CosmWasm enabled chain."
edition = "2021"
license = "MIT OR Apache-2.0"
name = "beaker"
version = "0.1.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
cargo-generate = {version = "0.18.3", features = ["vendored-openssl"]}
clap = {version = "4.2.7", features = ["derive","string"]}
config = {version = "0.13.1", features = ["preserve_order"]}
console = "0.15.0"
cosmos-sdk-proto = {version = "0.16", features = ["cosmwasm"]}
cosmrs = {version = "0.14.0", features = ["dev", "cosmwasm", "grpc"]}
data_doc = {version = "0.1.0", path = "../data_doc"}
data_doc_derive = {version = "0.1.0", path = "../data_doc_derive"}
derive-new = "0.5.9"
dialoguer = "0.10.1"
getset = "0.1.2"
keyring = "1.2.0"
prost = "0.11.8"
regex = "1.5.6"
rhai = {version = "1.12.0", features = ["serde"]}
rhai-fs = "0.1.2"
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8"
tendermint = "0.32.0"
tendermint-rpc = {version = "0.32.0", features = ["http-client"]}
textwrap = "0.15.0"
tokio = {version = "1.18.2", features = ["full"]}
toml = "0.5.9"

[dev-dependencies]
assert_fs = "1.0.7"
cargo_toml = "0.11.5"
predicates = "2.1.1"
pretty_assertions = "1.2.1"
serial_test = "0.6.0"
