[package]
description = "CosmWasm development tooling"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "beaker"
rust_version = "1.61"
version = "0.0.8"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
base64 = "0.13.0"
cargo-generate = {version = "0.15.2", features = ["vendored-openssl"]}
clap = {version = "3.2.5", features = ["derive"]}
config = {version = "0.13.1", features = ["preserve_order"]}
console = "0.15.0"
cosmos-sdk-proto = {version = "0.12.3", features = ["cosmwasm"]}
cosmrs = {version = "0.7.1", features = ["dev", "cosmwasm"]}
data_doc = {version = "0.1.0", path = "../data_doc"}
data_doc_derive = {version = "0.1.0", path = "../data_doc_derive"}
derive-new = "0.5.9"
dialoguer = "0.10.1"
getset = "0.1.2"
keyring = "1.2.0"
prost = "0.10.3"
regex = "1.5.6"
serde = "1.0.137"
serde_json = "1.0.81"
serde_yaml = "0.8"
tendermint-rpc = "0.23.7"
textwrap = "0.15.0"
tokio = {version = "1.18.2", features = ["full"]}
toml = "0.5.9"

[dev-dependencies]
assert_fs = "1.0.7"
cargo_toml = "0.11.5"
predicates = "2.1.1"
pretty_assertions = "1.2.1"
serial_test = "0.6.0"
