[package]
description = "Getting doc string at runtime"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "data_doc_derive"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
data_doc = {version = "0.1.0", path = "../data_doc"}
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = {version = "1.0.98", features = ["full", "extra-traits"]}

[dev-dependencies]
pretty_assertions = "1.2.1"
